<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Export Sheet Metal to DXF in SOLIDWORKS | SOLIDWORKS Macros Lib </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Export Sheet Metal to DXF in SOLIDWORKS | SOLIDWORKS Macros Lib ">
      
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      <meta name="docfx:rel" content="../">
      
      
      <meta name="docfx:docurl" content="https://github.com/BlueByteSystemsInc/SOLIDWORKSVBAMacros/blob/main/src/assembly_export_dxf.md/#L1">
      <meta name="loc:inThisArticle" content="In this article">
      <meta name="loc:searchResultsCount" content="{count} results for &quot;{query}&quot;">
      <meta name="loc:searchNoResults" content="No results for &quot;{query}&quot;">
      <meta name="loc:tocFilter" content="Filter by title">
      <meta name="loc:nextArticle" content="Next">
      <meta name="loc:prevArticle" content="Previous">
      <meta name="loc:themeLight" content="Light">
      <meta name="loc:themeDark" content="Dark">
      <meta name="loc:themeAuto" content="Auto">
      <meta name="loc:changeTheme" content="Change theme">
      <meta name="loc:copy" content="Copy">
      <meta name="loc:downloadPdf" content="Download PDF">

      <script type="module" src="./../public/docfx.min.js"></script>

      <script>
        const theme = localStorage.getItem('theme') || 'auto'
        document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
      </script>

  </head>

  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/fav.png" alt="SOLIDWORKS VBA Macros Lib">
            SOLIDWORKS VBA Macros Lib
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="">
<h1 id="export-sheet-metal-to-dxf-in-solidworks">Export Sheet Metal to DXF in SOLIDWORKS</h1>

<img src="../images/assembly_export_dxf.png" alt="Description of image" width="600" style="display: block; margin: 0 auto;">
<h2 id="macro-description">Macro Description</h2>
<p>This VBA macro automates the process of exporting all sheet metal parts from a SOLIDWORKS assembly to DXF files. The macro loops through each component in the assembly, checks if it's a sheet metal part, and exports the flat pattern of the part to a DXF file. The macro ensures that duplicate parts are not processed more than once, preventing redundant exports.</p>
<h2 id="vba-macro-code">VBA Macro Code</h2>
<pre><code class="lang-vbnet">Option Explicit
' ********************************************************************
' DISCLAIMER: 
' This code is provided as-is with no warranty or liability by 
' Blue Byte Systems Inc. The company assumes no responsibility for 
' any issues arising from the use of this code in production.
' ********************************************************************

' Enum for Sheet Metal export options
Enum SheetMetalOptions_e
    ExportFlatPatternGeometry = 1
    IncludeHiddenEdges = 2
    ExportBendLines = 4
    IncludeSketches = 8
    MergeCoplanarFaces = 16
    ExportLibraryFeatures = 32
    ExportFormingTools = 64
    ExportBoundingBox = 2048
End Enum

' solidworks app variable
Dim swApp As SldWorks.SldWorks
Dim swModelDoc As ModelDoc2
Dim swAssemblyDoc As AssemblyDoc
Dim swComponents As Variant
Dim swComponent As Component2
Dim swComponentIterator
Dim processedFiles() As String

Sub Main()


ReDim processedFiles(0)

processedFiles(0) = &quot;&quot;

 Set swApp = Application.SldWorks
 
 Set swModelDoc = swApp.ActiveDoc
 
 Set swAssemblyDoc = swModelDoc
 
 
 swComponents = swAssemblyDoc.GetComponents(False)

 For Each swComponentIterator In swComponents
  
  Set swComponent = swComponentIterator
  
  Dim swComponentModelDoc As ModelDoc2
  
  Set swComponentModelDoc = swComponent.GetModelDoc2
  
  If Not swComponentModelDoc Is Nothing Then
  
   If ExistsInProcessedFiles(processedFiles, swComponentModelDoc.GetPathName()) = False Then
   
   addItemToProcessedFiles processedFiles, swComponentModelDoc.GetPathName()
   
   PrintDXF swComponentModelDoc
   
   
   End If
   
  End If
 
  
 
 Next swComponentIterator

End Sub


Function ExistsInProcessedFiles(ByRef arr() As String, fileName As Variant) As Boolean



Dim i As Long

For i = LBound(arr) To UBound(arr)

 If arr(i) = fileName Then
 
  ExistsInProcessedFiles = True
  
  Exit Function
  
  End If

Next i

ExistsInProcessedFiles = False

End Function


Sub PrintDXF(ByRef swmodel As ModelDoc2)

If swmodel.GetType() = swDocumentTypes_e.swDocPART Then

 Dim swPart As PartDoc
 
 Set swPart = swmodel

 Dim modelPath As String
 
 modelPath = swmodel.GetPathName
 
 Dim outPath As String
 
 outPath = Left(modelPath, Len(modelPath) - 6)
 
 outPath = outPath + &quot;dxf&quot;
 
 swmodel.Visible = True
 
 Dim saveDXF As Boolean
 
 saveDXF = swPart.ExportToDWG2(outPath, modelPath, swConst.swExportToDWG_e.swExportToDWG_ExportSheetMetal, True, vbEmpty, False, False, SheetMetalOptions_e.ExportFlatPatternGeometry + SheetMetalOptions_e.ExportFlatPatternGeometry + SheetMetalOptions_e.ExportFlatPatternGeometry + SheetMetalOptions_e.ExportBendLines, vbEmpty)

 If saveDXF Then
 
  Debug.Print swmodel.GetTitle() &amp; &quot; saved&quot;
 
 
 Else
  Debug.Print swmodel.GetTitle() &amp; &quot; failed to save&quot;
 
 End If
 
 swmodel.Visible = False
 
End If

End Sub


Public Sub addItemToProcessedFiles(ByRef arr() As String, ByVal processedFile As String)

Dim arrLength As Long

arrLength = UBound(arr)

If arrLength &lt; 0 Then

ReDim arr(0)

arr(0) = processedFile

Else

ReDim Preserve arr(arrLength + 1)
 
arr(arrLength + 1) = processedFile

End If

End Sub

</code></pre>
<h2 id="system-requirements">System Requirements</h2>
<p>To run this VBA macro, ensure that your system meets the following requirements:</p>
<ul>
<li>SOLIDWORKS Version: SOLIDWORKS 2017 or later</li>
<li>VBA Environment: Pre-installed with SOLIDWORKS (Access via Tools &gt; Macro &gt; New or Edit)</li>
<li>Operating System: Windows 7, 8, 10, or later</li>
</ul>
<div class="NOTE">
<h5>Note</h5>
<p>Pre-conditions</p>
<ul>
<li>The active document must be an assembly (.sldasm) in SOLIDWORKS.</li>
<li>Ensure that the components contain valid sheet metal parts for export.</li>
</ul>
</div>
<div class="NOTE">
<h5>Note</h5>
<p>Post-conditions
The flat pattern of each sheet metal part will be exported as a DXF file.</p>
</div>
<h2 id="macro">Macro</h2>
<p>You can download the macro from <a href="../images/assembly_export_dxf.swp">here</a></p>
<h2 id="customization">Customization</h2>
<p>Need to modify the macro to meet specific requirements or integrate it with other processes? We provide custom macro development tailored to your needs. <a href="https://bluebyte.biz/contact">Contact us</a>.</p>

</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/BlueByteSystemsInc/SOLIDWORKSVBAMacros/blob/main/src/assembly_export_dxf.md/#L1" class="edit-link">Edit this page</a>
        </div>

        <div class="next-article d-print-none border-top" id="nextArticle"></div>

      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top text-secondary">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Hosted and provided by <a href='https://bluebyte.biz'>Blue Byte Systems Inc</a>. Made with Maple syrup 🍁 and Couscous 🍲.</span>
        </div>
      </div>
    </footer>
  </body>
</html>
