<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title>Link Note to Configuration Specific Property in SolidWorks | &#129513; SOLIDWORKS VBA Macros Library </title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="title" content="Link Note to Configuration Specific Property in SolidWorks | &#129513; SOLIDWORKS VBA Macros Library ">
      
      
      <link rel="icon" href="../favicon.ico">
      <link rel="stylesheet" href="../public/docfx.min.css">
      <link rel="stylesheet" href="../public/main.css">
      <meta name="docfx:navrel" content="../toc.html">
      <meta name="docfx:tocrel" content="toc.html">
      
      <meta name="docfx:rel" content="../">
      
      
      <meta name="docfx:docurl" content="https://github.com/BlueByteSystemsInc/SOLIDWORKSVBAMacros/blob/main/src/LinkNoteToConfig.md/#L1">
      <meta name="loc:inThisArticle" content="In this article">
      <meta name="loc:searchResultsCount" content="{count} results for &quot;{query}&quot;">
      <meta name="loc:searchNoResults" content="No results for &quot;{query}&quot;">
      <meta name="loc:tocFilter" content="Filter by title">
      <meta name="loc:nextArticle" content="Next">
      <meta name="loc:prevArticle" content="Previous">
      <meta name="loc:themeLight" content="Light">
      <meta name="loc:themeDark" content="Dark">
      <meta name="loc:themeAuto" content="Auto">
      <meta name="loc:changeTheme" content="Change theme">
      <meta name="loc:copy" content="Copy">
      <meta name="loc:downloadPdf" content="Download PDF">

      <script type="module" src="./../public/docfx.min.js"></script>

      <script>
        const theme = localStorage.getItem('theme') || 'auto'
        document.documentElement.setAttribute('data-bs-theme', theme === 'auto' ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light') : theme)
      </script>

  </head>

  <body class="tex2jax_ignore" data-layout="" data-yaml-mime="">
    <header class="bg-body border-bottom">
      <nav id="autocollapse" class="navbar navbar-expand-md" role="navigation">
        <div class="container-xxl flex-nowrap">
          <a class="navbar-brand" href="../index.html">
            <img id="logo" class="svg" src="../images/fav.png" alt="&#129513; SOLIDWORKS VBA Macros Library">
            &#129513; SOLIDWORKS VBA Macros Library
          </a>
          <button class="btn btn-lg d-md-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navpanel" aria-controls="navpanel" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-three-dots"></i>
          </button>
          <div class="collapse navbar-collapse" id="navpanel">
            <div id="navbar">
              <form class="search" role="search" id="search">
                <i class="bi bi-search"></i>
                <input class="form-control" id="search-query" type="search" disabled="" placeholder="Search" autocomplete="off" aria-label="Search">
              </form>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main class="container-xxl">
      <div class="toc-offcanvas">
        <div class="offcanvas-md offcanvas-start" tabindex="-1" id="tocOffcanvas" aria-labelledby="tocOffcanvasLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="tocOffcanvasLabel">Table of Contents</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#tocOffcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <nav class="toc" id="toc"></nav>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="actionbar">
          <button class="btn btn-lg border-0 d-md-none" style="margin-top: -.65em; margin-left: -.8em" type="button" data-bs-toggle="offcanvas" data-bs-target="#tocOffcanvas" aria-controls="tocOffcanvas" aria-expanded="false" aria-label="Show table of contents">
            <i class="bi bi-list"></i>
          </button>

          <nav id="breadcrumb"></nav>
        </div>

        <article data-uid="">
<h1 id="link-note-to-configuration-specific-property-in-solidworks">Link Note to Configuration Specific Property in SolidWorks</h1>

<h2 id="description">Description</h2>
<p>This macro allows users to link a note in a SolidWorks document to a configuration-specific property. The macro pushes the value of the note into a custom property in the configuration, but it does not update the note with changes in the property value. The macro prompts the user to enter the property name to which the selected note will be linked. Additionally, a macro feature is created, ensuring that the note and custom property linkage is maintained.</p>
<h2 id="system-requirements">System Requirements</h2>
<ul>
<li><strong>SolidWorks Version</strong>: SolidWorks 2014 or newer</li>
<li><strong>Operating System</strong>: Windows 7 or later</li>
</ul>
<h2 id="pre-conditions">Pre-Conditions</h2>
<div class="NOTE">
<h5>Note</h5>
<ul>
<li>The user must preselect a note in the SolidWorks model before running the macro.</li>
<li>The active document must support configuration-specific properties.</li>
<li>A valid name for the property should be provided in the input box on the UserForm.</li>
</ul>
</div>
<h2 id="results">Results</h2>
<div class="NOTE">
<h5>Note</h5>
<ul>
<li>The selected note's text is linked to a configuration-specific property with the specified name.</li>
<li>A macro feature is added to maintain this link, allowing the custom property to update as the note text changes.</li>
<li>A message box appears if no note is selected or if an invalid name is entered.</li>
</ul>
</div>
<h2 id="vba-macro-code">VBA Macro Code</h2>
<pre><code class="lang-vbnet">' Disclaimer:
' The code provided should be used at your own risk.  
' Blue Byte Systems Inc. assumes no responsibility for any issues or damages that may arise from using or modifying this code.  
' For more information, visit [Blue Byte Systems Inc.](https://bluebyte.biz).

Option Explicit

' Main subroutine to display the UserForm
Sub Main()
    UserForm1.Show
End Sub


' Create a Module named FeatureModule and paste the code Below
vbnet
Copy code
Option Explicit

' Rebuild routine for the macro feature
Function swmRebuild(varApp As Variant, varDoc As Variant, varFeat As Variant) As Variant
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swCusPropMgr As CustomPropertyManager
    Dim swCfgPropMgr As CustomPropertyManager
    
    Set swApp = varApp
    Set swModel = varDoc
    Set swCusPropMgr = swModel.Extension.CustomPropertyManager(&quot;&quot;)
    
    Dim CustomPropNames As Variant
    Dim CustomPropValues As Variant
    swCusPropMgr.GetAll CustomPropNames, Nothing, CustomPropValues
    
    Dim i As Integer
    If swCusPropMgr.Count = 0 Then Exit Function
    
    For i = LBound(CustomPropNames) To UBound(CustomPropNames)
        If Left(CustomPropNames(i), 9) = &quot;Linked - &quot; Then
            Set swCfgPropMgr = swModel.Extension.CustomPropertyManager(swModel.ConfigurationManager.ActiveConfiguration.name)
            swCfgPropMgr.Delete CustomPropValues(i)
            swCfgPropMgr.Add2 CustomPropValues(i), swCustomInfoText, GetNoteTextByName(Mid(CustomPropNames(i), 10))
        End If
    Next
End Function

' Function to get the text of a note by name
Function GetNoteTextByName(ByVal name As String)
    Dim swApp As SldWorks.SldWorks
    Dim swModel As ModelDoc2
    Dim swNote As Note
    Dim swSelMgr As SelectionMgr
    
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swSelMgr = swModel.SelectionManager
    
    swModel.Extension.SelectByID2 name &amp; &quot;@Annotations&quot;, &quot;NOTE&quot;, 0, 0, 0, False, -1, Nothing, swSelectOptionDefault
    Set swNote = swSelMgr.GetSelectedObject6(1, -1)
    If Not swNote Is Nothing Then GetNoteTextByName = swNote.GetText
End Function

' Edit definition routine for the macro feature
Function swmEditDefinition(varApp As Variant, varDoc As Variant, varFeat As Variant) As Variant
    UserForm1.Show
End Function

' Security routine for the macro feature
Function swmSecurity(varApp As Variant, varDoc As Variant, varFeat As Variant) As Variant
    swmSecurity = SwConst.swMacroFeatureSecurityOptions_e.swMacroFeatureSecurityByDefault
End Function

' Subroutine to create the macro feature if it doesn't already exist
Sub CreateNewMacroFeature(ByRef swApp As SldWorks.SldWorks)
    If Not LinkFeatureExists(swApp) Then
        Dim swModel As SldWorks.ModelDoc2
        Dim feat As Feature
        Dim Methods(8) As String
        Dim Names As Variant, Types As Variant, Values As Variant
        Dim options As Long
        Dim icons(2) As String

        Set swModel = swApp.ActiveDoc
        ThisFile = swApp.GetCurrentMacroPathName
        Methods(0) = ThisFile: Methods(1) = &quot;FeatureModule&quot;: Methods(2) = &quot;swmRebuild&quot;
        Methods(3) = ThisFile: Methods(4) = &quot;FeatureModule&quot;: Methods(5) = &quot;swmEditDefinition&quot;

        options = swMacroFeatureAlwaysAtEnd
        Set feat = swModel.FeatureManager.InsertMacroFeature3(&quot;Link Properties&quot;, &quot;&quot;, Methods, Names, Types, Values, Empty, Empty, Empty, icons, options)
        swModel.ForceRebuild3 False
    End If
End Sub

' Function to check if the macro feature already exists
Function LinkFeatureExists(ByRef swApp As SldWorks.SldWorks)
    Dim swModel As ModelDoc2
    Dim swFeat As Feature
    Set swModel = swApp.ActiveDoc
    LinkFeatureExists = False
    Set swFeat = swModel.FirstFeature
    Do Until swFeat Is Nothing
        If Left(swFeat.Name, Len(&quot;Link Properties&quot;)) = &quot;Link Properties&quot; Then
            LinkFeatureExists = True
            Exit Function
        End If
        Set swFeat = swFeat.GetNextFeature
    Loop
End Function

'End of Feature Module

'Create User Form With TestBox and 2 Command Buttons as Below
'textBox1
'CommandButton1
'CommandButton2

'Paste the below in the backcode of the User Form
Option Explicit

Private Sub CommandButton1_Click()
    Dim swApp As SldWorks.SldWorks
    Set swApp = Application.SldWorks

    If TextBox1.Text &lt;&gt; &quot;&quot; Then
        CreateNoteProperties TextBox1.Text
        CreateNewMacroFeature swApp
    Else
        MsgBox &quot;Enter a name first&quot;
    End If
End Sub

' Function to create custom properties for the note
Function CreateNoteProperties(ByVal OutputName As String) As String
    Dim swApp As SldWorks.SldWorks
    Dim swModel As ModelDoc2
    Dim swSelMgr As SelectionMgr
    Dim swNote As Note

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    Set swSelMgr = swModel.SelectionManager

    If swSelMgr.GetSelectedObjectCount2(-1) = 0 Or swSelMgr.GetSelectedObjectType3(1, -1) &lt;&gt; 15 Then
        MsgBox &quot;You must select a note to link first&quot;
        Exit Function
    End If

    Set swNote = swSelMgr.GetSelectedObject6(1, -1)
    If Not swNote Is Nothing Then
        CreateNoteProperties = swNote.GetText
        swModel.Extension.CustomPropertyManager(&quot;&quot;).Delete &quot;Linked - &quot; &amp; swNote.GetName
        swModel.Extension.CustomPropertyManager(&quot;&quot;).Add2 &quot;Linked - &quot; &amp; swNote.GetName, swCustomInfoText, OutputName
    End If
End Function

</code></pre>
<h2 id="customization">Customization</h2>
<p>Need to modify the macro to meet specific requirements or integrate it with other processes? We provide custom macro development tailored to your needs. <a href="https://bluebyte.biz/contact">Contact us</a>.</p>

</article>

        <div class="contribution d-print-none">
          <a href="https://github.com/BlueByteSystemsInc/SOLIDWORKSVBAMacros/blob/main/src/LinkNoteToConfig.md/#L1" class="edit-link">Edit this page</a>
        </div>

        <div class="next-article d-print-none border-top" id="nextArticle"></div>

      </div>

      <div class="affix">
        <nav id="affix"></nav>
      </div>
    </main>

    <div class="container-xxl search-results" id="search-results"></div>

    <footer class="border-top text-secondary">
      <div class="container-xxl">
        <div class="flex-fill">
          <span>Hosted and provided by <a href='https://bluebyte.biz'>Blue Byte Systems Inc</a>. Made with Maple syrup 🍁 and Couscous 🍲.</span>
        </div>
      </div>
    </footer>
  </body>
</html>
